{
    "tests": [
        {
            "traceback": "Traceback (most recent call last):\n  File \"/home/grader/first_neural_network/workspace/my_answers.py\", line 128, in run\n    features = features.to_numpy()\n  File \"/usr/local/lib/python3.5/dist-packages/pandas/core/generic.py\", line 3614, in __getattr__\n    return object.__getattribute__(self, name)\nAttributeError: 'DataFrame' object has no attribute 'to_numpy'\n",
            "rubric_item_id": 7965,
            "result": "E",
            "description": "Produces good results when running the network on full data"
        },
        {
            "traceback": "Traceback (most recent call last):\n  File \"/home/grader/first_neural_network/workspace/my_answers.py\", line 128, in run\n    features = features.to_numpy()\nAttributeError: 'numpy.ndarray' object has no attribute 'to_numpy'\n",
            "rubric_item_id": 5573,
            "result": "E",
            "description": "The run method is correct"
        },
        {
            "traceback": "",
            "rubric_item_id": 5574,
            "result": ".",
            "description": "The activation function is a sigmoid"
        },
        {
            "traceback": "",
            "rubric_item_id": 5578,
            "result": ".",
            "description": "The backpropagation implementation is correct"
        },
        {
            "traceback": "",
            "rubric_item_id": 5575,
            "result": ".",
            "description": "The number of epochs is reasonable"
        },
        {
            "traceback": "",
            "rubric_item_id": 5572,
            "result": ".",
            "description": "The forward pass implementation is correct"
        },
        {
            "traceback": "",
            "rubric_item_id": 5581,
            "result": ".",
            "description": "The number of hidden nodes is reasonable"
        },
        {
            "traceback": "",
            "rubric_item_id": 5582,
            "result": ".",
            "description": "The learning_rate is reasonable"
        },
        {
            "traceback": "",
            "rubric_item_id": 7964,
            "result": ".",
            "description": "The number of output nodes is correct"
        },
        {
            "traceback": "",
            "rubric_item_id": 5570,
            "result": ".",
            "description": "The weights are updated correctly on training"
        },
        {
            "traceback": "",
            "rubric_item_id": 5580,
            "result": ".",
            "description": "The update_weights implementation is correct"
        }
    ],
    "critiques": {
        "700": {
            "general_comment": null,
            "rubric_items": {
                "5570": {
                    "autograded": false,
                    "result": "passed",
                    "observation": "Correct!"
                },
                "5572": {
                    "autograded": false,
                    "result": "passed",
                    "observation": "Correct!"
                },
                "5573": {
                    "autograded": false,
                    "result": "failed",
                    "observation": "```\nNot all of the tests passed.\n\n\n************************************************************************\n                         Test Failure Feedback                          \n************************************************************************\n\nFailed Test: The run method is correct\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/grader/first_neural_network/workspace/my_answers.py\", line 128, in run\n    features = features.to_numpy()\nAttributeError: 'numpy.ndarray' object has no attribute 'to_numpy'\n\n\n************************************************************************\n                          Test Result Summary                           \n************************************************************************\n\nThe run method is correct                                              E\n\n\n```"
                },
                "5574": {
                    "autograded": false,
                    "result": "passed",
                    "observation": "Correct!"
                },
                "5575": {
                    "autograded": false,
                    "result": "passed",
                    "observation": "Correct!"
                },
                "5578": {
                    "autograded": false,
                    "result": "passed",
                    "observation": "Correct!"
                },
                "5580": {
                    "autograded": false,
                    "result": "passed",
                    "observation": "Correct!"
                },
                "5581": {
                    "autograded": false,
                    "result": "passed",
                    "observation": "Correct!"
                },
                "5582": {
                    "autograded": false,
                    "result": "passed",
                    "observation": "Correct!"
                },
                "7964": {
                    "autograded": false,
                    "result": "passed",
                    "observation": "Correct!"
                },
                "7965": {
                    "autograded": false,
                    "result": "failed",
                    "observation": "```\nNot all of the tests passed.\n\n\n************************************************************************\n                         Test Failure Feedback                          \n************************************************************************\n\nFailed Test: Produces good results when running the network on full data\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/grader/first_neural_network/workspace/my_answers.py\", line 128, in run\n    features = features.to_numpy()\n  File \"/usr/local/lib/python3.5/dist-packages/pandas/core/generic.py\", line 3614, in __getattr__\n    return object.__getattribute__(self, name)\nAttributeError: 'DataFrame' object has no attribute 'to_numpy'\n\n\n************************************************************************\n                          Test Result Summary                           \n************************************************************************\n\nProduces good results when running the network on full data            E\n\n\n```"
                }
            }
        }
    }
}